//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsmsQuiz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizType
    {
        public QuizType()
        {
            this.QuizSessions = new HashSet<QuizSession>();
        }
    
        public long QuizTypeID { get; set; }
        public string QuizTypeName { get; set; }
    
        public virtual ICollection<QuizSession> QuizSessions { get; set; }
    }
}
