//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsmsQuiz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizSessionUserAnswer
    {
        public long QuizSessionUserAnswerID { get; set; }
        public long QuizSessionID { get; set; }
        public long QuizQuestionID { get; set; }
        public long QuizSessionUserID { get; set; }
        public Nullable<int> UserAnswer { get; set; }
    
        public virtual QuizQuestion QuizQuestion { get; set; }
        public virtual QuizSessionUser QuizSessionUser { get; set; }
    }
}
