//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsmsQuiz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizSecurityQuestion
    {
        public long QuizSessionQuestionID { get; set; }
        public string SecurityQuestion { get; set; }
        public int NoOfAnswer { get; set; }
        public string Answer1 { get; set; }
        public int CorrectAnswer { get; set; }
    }
}
