//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsmsQuiz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestion
    {
        public QuizQuestion()
        {
            this.QuizSessionUserAnswers = new HashSet<QuizSessionUserAnswer>();
        }
    
        public long QuizQuestionID { get; set; }
        public long QuizSessionID { get; set; }
        public string QuizQuestionName { get; set; }
        public int NoOfAnswer { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public string Answer3 { get; set; }
        public string Answer4 { get; set; }
        public string Answer5 { get; set; }
        public bool HasAnswer { get; set; }
        public int CorrectAnswer { get; set; }
    
        public virtual QuizSession QuizSession { get; set; }
        public virtual ICollection<QuizSessionUserAnswer> QuizSessionUserAnswers { get; set; }
    }
}
