//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsmsQuiz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizSession
    {
        public QuizSession()
        {
            this.QuizQuestions = new HashSet<QuizQuestion>();
            this.QuizSessionUsers = new HashSet<QuizSessionUser>();
        }
    
        public long QuizSessionID { get; set; }
        public long QuizAdminID { get; set; }
        public string QuizSessionName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Purpose { get; set; }
        public long QuizTypeID { get; set; }
    
        public virtual QuizAdmin QuizAdmin { get; set; }
        public virtual ICollection<QuizQuestion> QuizQuestions { get; set; }
        public virtual QuizType QuizType { get; set; }
        public virtual ICollection<QuizSessionUser> QuizSessionUsers { get; set; }
    }
}
