//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackOverflow_Solve.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.SpareInfosSoap")]
    public interface SpareInfosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDropDownListBindings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDropDownListBindings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSpareParts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getSpareParts();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SpareInfosSoapChannel : StackOverflow_Solve.ServiceReference2.SpareInfosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpareInfosSoapClient : System.ServiceModel.ClientBase<StackOverflow_Solve.ServiceReference2.SpareInfosSoap>, StackOverflow_Solve.ServiceReference2.SpareInfosSoap {
        
        public SpareInfosSoapClient() {
        }
        
        public SpareInfosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpareInfosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpareInfosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpareInfosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDropDownListBindings() {
            return base.Channel.GetDropDownListBindings();
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public string getSpareParts() {
            return base.Channel.getSpareParts();
        }
    }
}
