//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace StackOverflow_Solve.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WaltonCrmEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WaltonCrmEntities object using the connection string found in the 'WaltonCrmEntities' section of the application configuration file.
        /// </summary>
        public WaltonCrmEntities() : base("name=WaltonCrmEntities", "WaltonCrmEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WaltonCrmEntities object.
        /// </summary>
        public WaltonCrmEntities(string connectionString) : base(connectionString, "WaltonCrmEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WaltonCrmEntities object.
        /// </summary>
        public WaltonCrmEntities(EntityConnection connection) : base(connection, "WaltonCrmEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SparePart> SpareParts
        {
            get
            {
                if ((_SpareParts == null))
                {
                    _SpareParts = base.CreateObjectSet<SparePart>("SpareParts");
                }
                return _SpareParts;
            }
        }
        private ObjectSet<SparePart> _SpareParts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SpareParts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSpareParts(SparePart sparePart)
        {
            base.AddObject("SpareParts", sparePart);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WaltonCrmModel", Name="SparePart")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SparePart : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SparePart object.
        /// </summary>
        /// <param name="itemID">Initial value of the ItemID property.</param>
        /// <param name="itemCode">Initial value of the ItemCode property.</param>
        /// <param name="itemName">Initial value of the ItemName property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        /// <param name="minorCategory">Initial value of the MinorCategory property.</param>
        public static SparePart CreateSparePart(global::System.Int64 itemID, global::System.String itemCode, global::System.String itemName, global::System.Boolean isActive, global::System.String minorCategory)
        {
            SparePart sparePart = new SparePart();
            sparePart.ItemID = itemID;
            sparePart.ItemCode = itemCode;
            sparePart.ItemName = itemName;
            sparePart.IsActive = isActive;
            sparePart.MinorCategory = minorCategory;
            return sparePart;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ItemID
        {
            get
            {
                return _ItemID;
            }
            set
            {
                if (_ItemID != value)
                {
                    OnItemIDChanging(value);
                    ReportPropertyChanging("ItemID");
                    _ItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemID");
                    OnItemIDChanged();
                }
            }
        }
        private global::System.Int64 _ItemID;
        partial void OnItemIDChanging(global::System.Int64 value);
        partial void OnItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemCode
        {
            get
            {
                return _ItemCode;
            }
            set
            {
                OnItemCodeChanging(value);
                ReportPropertyChanging("ItemCode");
                _ItemCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemCode");
                OnItemCodeChanged();
            }
        }
        private global::System.String _ItemCode;
        partial void OnItemCodeChanging(global::System.String value);
        partial void OnItemCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemName
        {
            get
            {
                return _ItemName;
            }
            set
            {
                OnItemNameChanging(value);
                ReportPropertyChanging("ItemName");
                _ItemName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemName");
                OnItemNameChanged();
            }
        }
        private global::System.String _ItemName;
        partial void OnItemNameChanging(global::System.String value);
        partial void OnItemNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ItemPrice
        {
            get
            {
                return _ItemPrice;
            }
            set
            {
                OnItemPriceChanging(value);
                ReportPropertyChanging("ItemPrice");
                _ItemPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemPrice");
                OnItemPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _ItemPrice;
        partial void OnItemPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnItemPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemDesc
        {
            get
            {
                return _ItemDesc;
            }
            set
            {
                OnItemDescChanging(value);
                ReportPropertyChanging("ItemDesc");
                _ItemDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemDesc");
                OnItemDescChanged();
            }
        }
        private global::System.String _ItemDesc;
        partial void OnItemDescChanging(global::System.String value);
        partial void OnItemDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ItemGroup
        {
            get
            {
                return _ItemGroup;
            }
            set
            {
                OnItemGroupChanging(value);
                ReportPropertyChanging("ItemGroup");
                _ItemGroup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemGroup");
                OnItemGroupChanged();
            }
        }
        private Nullable<global::System.Int32> _ItemGroup;
        partial void OnItemGroupChanging(Nullable<global::System.Int32> value);
        partial void OnItemGroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MajorCategory
        {
            get
            {
                return _MajorCategory;
            }
            set
            {
                OnMajorCategoryChanging(value);
                ReportPropertyChanging("MajorCategory");
                _MajorCategory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MajorCategory");
                OnMajorCategoryChanged();
            }
        }
        private global::System.String _MajorCategory;
        partial void OnMajorCategoryChanging(global::System.String value);
        partial void OnMajorCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MinorCategory
        {
            get
            {
                return _MinorCategory;
            }
            set
            {
                OnMinorCategoryChanging(value);
                ReportPropertyChanging("MinorCategory");
                _MinorCategory = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MinorCategory");
                OnMinorCategoryChanged();
            }
        }
        private global::System.String _MinorCategory;
        partial void OnMinorCategoryChanging(global::System.String value);
        partial void OnMinorCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UOM
        {
            get
            {
                return _UOM;
            }
            set
            {
                OnUOMChanging(value);
                ReportPropertyChanging("UOM");
                _UOM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UOM");
                OnUOMChanged();
            }
        }
        private global::System.String _UOM;
        partial void OnUOMChanging(global::System.String value);
        partial void OnUOMChanged();

        #endregion

    
    }

    #endregion

    
}
